### ISSUE TITLE
https für cryptoparty-hamburg.de

### ISSUE THREAD

**Issue by chatcannon** [ccchh/Cryptoparty-Slides#1]
Danach passen die Link auf der ersten Folie an.

**Comment by melzai** [comment]
Done. Wobei man da vielleicht noch erwähnen sollte, dass man der Sicherheitsausnahme zustimmen sollte?

**Comment by llf42** [comment]
https haben wir ja schon länger, aber die Browser-Warnungen wegen des selbstsignierten Zertifikats sind halt unschön und haben mehrfach zu besorgten Nachfragen geführt. Es wäre schön, wenn wir dies mit einem entsprechend signierten Zertifikat vermeiden könnten.

**Comment by llf42** [comment]
Seit Dienstag läuft die Seite mit Let's Encrypt
